# Generated by Django 3.2.20 on 2025-10-14 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icvybz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('audio_type', models.CharField(choices=[('dialogue', 'Dialogue Voice'), ('sound_effect', 'Sound Effect'), ('music', 'Background Music'), ('ambient', 'Ambient Sound'), ('transition', 'Scene Transition'), ('intro', 'Episode Intro'), ('outro', 'Episode Outro'), ('action', 'Action Sound'), ('emotion', 'Emotional Music'), ('environmental', 'Environmental Sound')], max_length=20)),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('duration', models.FloatField(help_text='Duration in seconds')),
                ('volume', models.FloatField(default=1.0, help_text='Volume level (0.0 to 1.0)')),
                ('loop', models.BooleanField(default=False, help_text='Whether audio should loop')),
                ('fade_in', models.FloatField(default=0.0, help_text='Fade in duration in seconds')),
                ('fade_out', models.FloatField(default=0.0, help_text='Fade out duration in seconds')),
                ('position_x', models.FloatField(default=0.0, help_text='X position in 3D space')),
                ('position_y', models.FloatField(default=0.0, help_text='Y position in 3D space')),
                ('position_z', models.FloatField(default=0.0, help_text='Z position in 3D space')),
                ('max_distance', models.FloatField(default=10.0, help_text='Maximum audible distance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_audio_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_studios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SceneAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_ambient', models.ForeignKey(blank=True, limit_choices_to={'audio_type': 'ambient'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_background', to='icvybz.audiotrack')),
                ('environmental_sound', models.ForeignKey(blank=True, limit_choices_to={'audio_type': 'environmental'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_environmental', to='icvybz.audiotrack')),
                ('scene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='icvybz.scene')),
                ('transition_audio', models.ForeignKey(blank=True, limit_choices_to={'audio_type': 'transition'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_transition', to='icvybz.audiotrack')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_music', models.ForeignKey(blank=True, limit_choices_to={'audio_type': 'music'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episode_action_music', to='icvybz.audiotrack')),
                ('ambient_sound', models.ForeignKey(blank=True, limit_choices_to={'audio_type': 'ambient'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episode_ambient', to='icvybz.audiotrack')),
                ('emotional_music', models.ForeignKey(blank=True, limit_choices_to={'audio_type': 'emotion'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episode_emotional', to='icvybz.audiotrack')),
                ('environmental', models.ForeignKey(blank=True, limit_choices_to={'audio_type': 'environmental'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episode_environmental', to='icvybz.audiotrack')),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='icvybz.episode')),
                ('intro_audio', models.ForeignKey(blank=True, limit_choices_to={'audio_type': 'intro'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episode_intro', to='icvybz.audiotrack')),
                ('main_theme', models.ForeignKey(blank=True, limit_choices_to={'audio_type': 'music'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episode_main_theme', to='icvybz.audiotrack')),
                ('outro_audio', models.ForeignKey(blank=True, limit_choices_to={'audio_type': 'outro'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episode_outro', to='icvybz.audiotrack')),
            ],
        ),
        migrations.CreateModel(
            name='DialogueAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_delay', models.FloatField(default=0.0, help_text='Delay before audio starts (seconds)')),
                ('sync_with_text', models.BooleanField(default=True, help_text='Sync audio with text display')),
                ('action_sound', models.ForeignKey(blank=True, limit_choices_to={'audio_type': 'action'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogue_action', to='icvybz.audiotrack')),
                ('dialogue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='icvybz.dialogue')),
                ('sound_effect', models.ForeignKey(blank=True, limit_choices_to={'audio_type': 'sound_effect'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogue_sfx', to='icvybz.audiotrack')),
                ('voice_track', models.ForeignKey(blank=True, limit_choices_to={'audio_type': 'dialogue'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogue_voices', to='icvybz.audiotrack')),
            ],
        ),
        migrations.CreateModel(
            name='StudioCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('writer', 'Writer'), ('3d_artist', '3D Artist'), ('voice_actor', 'Voice Actor'), ('sound_engineer', 'Sound Engineer'), ('cinematographer', 'Cinematographer')], max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='icvybz.studio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('studio', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StoryCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('writer', 'Writer'), ('3d_artist', '3D Artist'), ('voice_actor', 'Voice Actor'), ('sound_engineer', 'Sound Engineer'), ('cinematographer', 'Cinematographer')], max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='icvybz.comic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('story', 'user')},
            },
        ),
    ]
