# Generated by Django 3.2.20 on 2025-10-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icvybz', '0002_audiotrack_dialogueaudio_episodeaudio_sceneaudio_storycollaborator_studio_studiocollaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
    ]
