# Generated by Django 3.2.20 on 2025-10-17 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icvybz', '0006_auto_20251016_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialogue',
            name='pov',
        ),
        migrations.AddField(
            model_name='dialogue',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='icvybz.character'),
        ),
    ]
