# Generated by Django 3.2.20 on 2025-10-19 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icvybz', '0007_auto_20251017_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='story',
            field=models.ForeignKey(blank=True, help_text='Story this character belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='icvybz.comic'),
        ),
    ]
