# Generated by Django 3.2.20 on 2025-10-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icvybz', '0008_add_story_to_character'),
    ]

    operations = [
    ]
