# Generated by Django 3.2.20 on 2025-11-14 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icvybz', '0011_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioCollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('writer', 'Writer'), ('3d_artist', '3D Artist'), ('voice_actor', 'Voice Actor'), ('sound_engineer', 'Sound Engineer'), ('cinematographer', 'Cinematographer')], default='writer', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='collaborationinvite',
            name='unique_invitation',
        ),
        migrations.RemoveConstraint(
            model_name='storycollaborator',
            name='unique_collaborator',
        ),
        migrations.AlterUniqueTogether(
            name='collaborationinvite',
            unique_together={('inviter', 'invitee_email', 'story')},
        ),
        migrations.AddField(
            model_name='studiocollaborationrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_collaboration_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studiocollaborationrequest',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_requests', to='icvybz.studio'),
        ),
        migrations.AddIndex(
            model_name='studiocollaborationrequest',
            index=models.Index(fields=['studio', 'status'], name='icvybz_stud_studio__c8b063_idx'),
        ),
        migrations.AddIndex(
            model_name='studiocollaborationrequest',
            index=models.Index(fields=['requester', 'status'], name='icvybz_stud_request_59d394_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studiocollaborationrequest',
            unique_together={('studio', 'requester')},
        ),
    ]
