# Generated by Django 3.2.20 on 2025-11-17 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icvybz', '0012_auto_20251114_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='pov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='icvybz.pov'),
        ),
    ]
