# Generated by Django 3.2.20 on 2025-11-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icvybz', '0013_restore_pov_to_dialogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Make this season visible to other users (requires story to also be public)'),
        ),
    ]
