# Generated by Django 3.2.20 on 2025-12-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icvybz', '0014_add_season_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiocollaborator',
            name='removed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when collaborator was removed', null=True),
        ),
    ]
