# Generated by Django 3.2.20 on 2024-05-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0002_article_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
