# Generated by Django 3.2.20 on 2024-05-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0003_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
