# Generated by Django 3.2.20 on 2025-01-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0003_siteimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimage',
            name='object_id',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
