# Generated by Django 3.2.20 on 2023-08-05 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0003_auto_20230728_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimage',
            name='about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_image', to='snmov.about'),
        ),
    ]
