# Generated by Django 3.2.20 on 2024-05-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0004_about_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='created',
            new_name='created_at',
        ),
    ]
