# Generated by Django 3.2.20 on 2023-08-05 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0004_alter_siteimage_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimage',
            name='about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_image', to='snmov.about'),
        ),
    ]
