# Generated by Django 3.2.20 on 2024-05-25 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0005_rename_created_preference_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='created',
            new_name='created_at',
        ),
    ]
