# Generated by Django 3.2.20 on 2024-05-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0006_rename_created_about_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraftCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
