# Generated by Django 3.2.20 on 2024-05-25 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0007_auto_20240525_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='reachout',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
