# Generated by Django 3.2.20 on 2024-05-27 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0008_reachout_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snmov.craftcategory')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snmov.craft')),
            ],
        ),
        migrations.CreateModel(
            name='CraftImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='craft_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('craft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='craft_images', to='snmov.craft')),
            ],
        ),
    ]
