# Generated by Django 3.2.20 on 2024-05-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0009_craft_craftimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='craft',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
