# Generated by Django 3.2.20 on 2024-05-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0010_craft_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craft',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
