# Generated by Django 3.2.20 on 2024-09-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0011_alter_craft_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gif_model',
            field=models.ImageField(blank=True, null=True, upload_to='gif_models/'),
        ),
    ]
