# Generated by Django 5.2.3 on 2025-08-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0012_article_gif_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='reachout',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reachout',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
