# Generated by Django 3.2.20 on 2025-05-17 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0002_update_site_domain'),
        ('snmov', '0015_auto_20250517_0001'),
    ]

    operations = [
    ]
