# Generated by Django 3.2.20 on 2025-05-18 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('snmov', '0016_merge_0002_update_site_domain_0015_auto_20250517_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimage',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='object_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='snmov.product'),
        ),
    ]
