# Generated by Django 3.2.20 on 2025-12-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0019_add_saved_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnotification',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Whether back-in-stock notification has been sent'),
        ),
        migrations.AddField(
            model_name='productnotification',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the back-in-stock notification was sent', null=True),
        ),
    ]
