# Generated by Django 3.2.20 on 2025-12-03 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snmov', '0022_add_newsletter_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('brute_force_attempt', 'Brute Force Attempt'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('unauthorized_access', 'Unauthorized Access'), ('file_upload', 'File Upload'), ('payment_processed', 'Payment Processed'), ('data_export', 'Data Export'), ('data_deletion', 'Data Deletion'), ('password_reset', 'Password Reset'), ('api_access', 'API Access'), ('suspicious_activity', 'Suspicious Activity')], max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional event details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Log',
                'verbose_name_plural': 'Security Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('terms_of_service', 'Terms of Service'), ('cookies', 'Cookie Consent'), ('marketing', 'Marketing Emails'), ('analytics', 'Analytics Tracking')], max_length=50)),
                ('consented', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('version', models.CharField(help_text='Version of policy/terms consented to', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Consent',
                'verbose_name_plural': 'Data Consents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['event_type', 'created_at'], name='snmov_secur_event_t_3a2a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['ip_address', 'created_at'], name='snmov_secur_ip_addr_61c3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['user', 'created_at'], name='snmov_secur_user_id_033124_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['severity', 'created_at'], name='snmov_secur_severit_bd1635_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dataconsent',
            unique_together={('user', 'consent_type')},
        ),
    ]
