"""
Django settings for snm project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import dj_database_url
import mimetypes
from configparser import RawConfigParser

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(
    os.path.abspath(os.path.join(__file__, os.pardir))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
config = RawConfigParser()
config.read('/etc/vybz/settings.ini')
#SECRET_KEY = os.environ.get('SNM_KEY')
SECRET_KEY = config.get('section', 'VYBZ_KEY')
STRIPE_PUBLIC_KEY = config.get('section','STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = config.get('section', 'STRIPE_SECRET_KEY')

SHIPPO_API_KEY=config.get('section', 'SHIPPO_LIVE')


META_SITE_PROTOCOL = 'http', 'https'


ROOT_URLCONF = 'snm.urls'

LOGIN_REDIRECT_URL = 'homepage'

LOGIN_URL = 'login_req'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'snmov',
    'icvybz',
    'crispy_forms',
    'storages',
    'django.contrib.sitemaps',
    'tinymce',
    'meta',
    'crispy_bootstrap4',
    'bootstrap4',
    
]

SITE_ID = 1
SITE_DOMAIN = 'justvybz.com'
SITE_NAME = 'Justvybz'

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap4'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TINYMCE_DEFAULT_CONFIG = {
    'height': 360,
    'width': 'auto',
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    # 'content_css': '../static-root/snmov/css/sm.css',
    'contents_style': 'body {font-family: Cabin; }',
    'theme': 'modern',
    'plugins': '''
            textcolor save link image media preview codesample contextmenu
            table code lists fullscreen  insertdatetime  nonbreaking
            contextmenu directionality searchreplace wordcount visualblocks
            visualchars code fullscreen autolink lists  charmap print  hr
            anchor pagebreak emoticons
            ''',
    'toolbar1': '''
            fullscreen preview bold italic underline | fontselect,
            fontsizeselect  | forecolor backcolor | alignleft alignright |
            aligncenter alignjustify | indent outdent | bullist numlist table |
            | link image media | codesample | emoticons |
            ''',
    'toolbar2': '''
            visualblocks visualchars |
            charmap hr pagebreak nonbreaking anchor |  code |
            ''',
    'contextmenu': 'formats | link image',
    'menubar': True,
    'statusbar': True,
}

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "snm.context_processors.cart_context",
                "snm.context_processors.cart_count",
            ],
        },
    },
]

WSGI_APPLICATION = 'snm.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Toronto'

USE_I18N = True

USE_L10N = True


db_from_env = dj_database_url.config(conn_max_age=500)
# DATABASES['default'].update(db_from_env)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Force HTTPS for password reset emails
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'

# Email configuration
DEFAULT_FROM_EMAIL = 'noreply@justvybz.com'
SUPPORT_EMAIL = 'support@justvybz.com'

EMAIL_HOST = 'mail.papamail.net'
EMAIL_PORT = 587
EMAIL_HOST_USER = config.get('section', 'VYBZ_FB_USER')
EMAIL_HOST_PASSWORD = config.get('section', 'VYBZ_FB_PASS')
EMAIL_USE_TLS = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/


STATIC_ROOT = os.path.join(BASE_DIR, 'live-static',
                           'static-root')  # live cdn AWS S3

# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# File upload settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'frontend', 'build'),  # React build folder for production static files
]

# Default Sender Address (fallback if admin user's address is not found)
DEFAULT_SENDER_NAME = 'Justvybz Inc.'
DEFAULT_SENDER_STREET1 = '206 Winston Blvd'
DEFAULT_SENDER_STREET2 = ''
DEFAULT_SENDER_CITY = 'Cambridge'
DEFAULT_SENDER_STATE = 'ON'
DEFAULT_SENDER_ZIP = 'N3C 1M3'
DEFAULT_SENDER_COUNTRY = 'CA'

# Debug settings - ensure error pages are shown in production
DEBUG = False  # This should be True in local.py and False in pro.py

# Allow hosts
ALLOWED_HOSTS = [
    'justvybz.com',
    'www.justvybz.com',
]

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True
