"""
Django settings for snm project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import dj_database_url
import mimetypes
from configparser import RawConfigParser

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(os.path.join(__file__, os.pardir))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
config = RawConfigParser()
config.read('/etc/snmov/settings.ini')
#SECRET_KEY = os.environ.get('SNM_KEY')
SECRET_KEY = config.get('section', 'SNM_KEY')


META_SITE_PROTOCOL = 'http', 'https'
META_SITE_DOMAIN = 'misteruzo.com'

LOGIN_REDIRECT_URL = 'homepage'

LOGIN_URL = 'login_req'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'snmov.apps.SnmovConfig',
    'crispy_forms',
    'crispy_bootstrap5',
    'storages',
    'django.contrib.sitemaps',
    'tinymce',
    'meta',
    'tilf',
    'vybcheq',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = 'bootstrap5'

TINYMCE_DEFAULT_CONFIG = {
    'height': 240,
    'width': 'auto',
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    'content_style': 'body {font-family: Cabin; color: rgb(52, 73, 94);}',

    'theme': 'silver',
    'plugins': '''
            textcolor save link image media preview codesample contextmenu
            table code lists fullscreen insertdatetime nonbreaking
            contextmenu directionality searchreplace wordcount visualblocks
            visualchars code fullscreen autolink lists charmap print hr
            anchor pagebreak emoticons
            ''',
    'toolbar1': '''
            fullscreen preview bold italic underline | fontselect,
            fontsizeselect | forecolor backcolor | alignleft alignright |
            aligncenter alignjustify | indent outdent | bullist numlist table |
            | link image media | emoticons |
            ''',
    'toolbar2': '''
            visualblocks visualchars |
            charmap hr  nonbreaking anchor |  code |
            ''',
    'contextmenu': 'formats | link image',
    'menubar': True,
    'statusbar': True,
    'paste_as_text': True,
    'forced_root_block': False,
    'codesample_languages': [
        {'text': 'HTML/XML', 'value': 'markup'},
        {'text': 'JavaScript', 'value': 'javascript'},
        {'text': 'CSS', 'value': 'css'},
        {'text': 'PHP', 'value': 'php'},
        {'text': 'Python', 'value': 'python'},
        {'text': 'Java', 'value': 'java'},
        {'text': 'C', 'value': 'c'},
        {'text': 'C++', 'value': 'cpp'}
    ],
    'codesample_global_prismjs': True,
    'external_plugins': {
        'codesample': '/static/tinymce/plugins/codesample/plugin.min.js'
    },
    'content_css': [
        '/static/tinymce/css/prism.css'
    ],
    'external_js': [
        '/static/tinymce/js/prism.js'
    ]
}

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'snm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'snm.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Toronto'

USE_I18N = True

USE_L10N = True

USE_TZ = True

mimetypes.add_type("image/svg+xml", ".svg", True)
mimetypes.add_type("image/svg+sml", ".svgz", True)




db_from_env = dj_database_url.config(conn_max_age=500)
#DATABASES['default'].update(db_from_env)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

DEFAULT_FROM_EMAIL = config.get('section','MG_USER')
EMAIL_HOST = 'mail.papamail.net'
EMAIL_PORT = 587
EMAIL_HOST_USER = config.get('section','MG_USER')
EMAIL_HOST_PASSWORD = config.get('section', 'MG_PASS')
EMAIL_USE_TLS = True

# Vybcheq — Financial Modeling Prep (EOD prices); key in /etc/snmov/settings.ini [section] FMP_API_KEY
VYBCHEQ_FMP_API_KEY = config.get(
    "section",
    "FMP_API_KEY",
    fallback=os.environ.get("VYBCHEQ_FMP_API_KEY", ""),
)
# FMP free tier: max ~5 years EOD history and 250 API calls/day. Raise on paid plans.
VYBCHEQ_FMP_EOD_YEARS = int(os.environ.get("VYBCHEQ_FMP_EOD_YEARS", "5"))
# FMP free tier: quarterly ratios/key-metrics allow limit ≤ 5. Raise on paid plans.
VYBCHEQ_FMP_QUARTERLY_LIMIT = int(os.environ.get("VYBCHEQ_FMP_QUARTERLY_LIMIT", "5"))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Static file serving
# STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'





