"""
Django settings for snm project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import dj_database_url
import mimetypes
from configparser import RawConfigParser

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(
    os.path.abspath(os.path.join(__file__, os.pardir))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# Debug mode
# Default to False in base; `snm.settings.local` should enable DEBUG for dev.
DEBUG = False

# SECURITY WARNING: keep the secret key used in production secret!
config = RawConfigParser()
config.read('/etc/vybz/settings.ini')
#SECRET_KEY = os.environ.get('SNM_KEY')
SECRET_KEY = config.get('section', 'VYBZ_KEY')

# Stripe API Configuration
# Base settings use DEVELOPMENT (test) keys by default
# Production settings (pro.py) will override to use production (live) keys
STRIPE_DEVELOPMENT_PUBLIC_KEY = config.get('section', 'STRIPE_DEV_PUBLIC_KEY', fallback='')
STRIPE_DEVELOPMENT_SECRET_KEY = config.get('section', 'STRIPE_DEV_SECRET_KEY', fallback='')

STRIPE_PRODUCTION_PUBLIC_KEY = config.get('section', 'STRIPE_PROD_PUBLIC_KEY', fallback='')
STRIPE_PRODUCTION_SECRET_KEY = config.get('section', 'STRIPE_PROD_SECRET_KEY', fallback='')

# Base settings: Use DEVELOPMENT (test) keys by default
# Production settings (pro.py) will override to use production keys
STRIPE_PUBLIC_KEY = STRIPE_DEVELOPMENT_PUBLIC_KEY
STRIPE_SECRET_KEY = STRIPE_DEVELOPMENT_SECRET_KEY
# Stripe webhook signing secret (Dashboard → Developers → Webhooks). Required in production for reliable fulfillment.
STRIPE_WEBHOOK_SECRET = config.get('section', 'STRIPE_WEBHOOK_SECRET', fallback='')

# Public URL of the React app (order links in emails, Stripe success/cancel URLs)
FRONTEND_URL = config.get('section', 'FRONTEND_URL', fallback='http://localhost:3000')


# Canada Post Developer Portal API Configuration
# Key Number format: "username : password" or "Key Number (username : password)"
# Base settings use DEVELOPMENT credentials by default
CANADAPOST_DEVELOPMENT_KEY_NUMBER = config.get('section', 'CANADAPOST_DEV_KEY_NUMBER', fallback='')
CANADAPOST_DEVELOPMENT_CUSTOMER_NUMBER = config.get('section', 'CANADAPOST_DEV_CUSTOMER_NUMBER', fallback='')

CANADAPOST_PRODUCTION_KEY_NUMBER = config.get('section', 'CANADAPOST_PROD_KEY_NUMBER', fallback='')
CANADAPOST_PRODUCTION_CUSTOMER_NUMBER = config.get('section', 'CANADAPOST_PROD_CUSTOMER_NUMBER', fallback='')

# Base settings: Use DEVELOPMENT API by default
# Production settings (pro.py) will override this to True
CANADAPOST_USE_PRODUCTION = False

# Set active credentials to development (base/local)
CANADAPOST_KEY_NUMBER = CANADAPOST_DEVELOPMENT_KEY_NUMBER
CANADAPOST_CUSTOMER_NUMBER = CANADAPOST_DEVELOPMENT_CUSTOMER_NUMBER

# Checkout: only offer these Canada Post domestic services (see Canada Post rate API docs).
# DOM.RP = Regular Parcel, DOM.EP = Expedited Parcel (not Priority/Xpresspost).
CANADAPOST_CHECKOUT_SERVICE_CODES = ['DOM.RP', 'DOM.EP']

# Labels shown at checkout (Canada Post returns names like "Expedited Parcel", "Regular Parcel").
CANADAPOST_CHECKOUT_SERVICE_LABELS = {
    'DOM.RP': 'Regular shipping',
    'DOM.EP': 'Expedited shipping',
}


# Return/Refund System Configuration
DEFAULT_RETURN_WINDOW_DAYS = 30  # Default return window in days
RETURN_SHIPPING_PAID_BY = 'customer'  # Options: 'customer' or 'store'
RESTOCKING_FEE_PERCENTAGE = 0  # Default restocking fee (0-100)
ENABLE_PARTIAL_RETURNS = True  # Allow partial returns from same order
STRIPE_REFUND_ENABLED = True  # Enable Stripe refund processing

# Stripe chargeback / dispute ops
DISPUTE_ALERT_EMAIL = ''  # Falls back to SUPPORT_EMAIL when blank
DISPUTE_TREND_WINDOW_HOURS = 24
DISPUTE_TREND_THRESHOLD = 3  # Open/created disputes in window → trending alert
DISPUTE_TRENDING_COOLDOWN_SECONDS = 6 * 60 * 60  # Avoid alert spam

# Tax Configuration
TAX_RATE = 0.13  # Default tax rate (13% for HST in Ontario, Canada) - can be overridden per province
TAX_ENABLED = True  # Enable tax calculation on invoices
# When True, Stripe Checkout includes a separate line item for tax (must match invoice PDF logic)
STRIPE_CHECKOUT_INCLUDE_TAX = True

# Returns: order statuses that may start a return (adjust per policy)
RETURN_ELIGIBLE_STATUSES = ('DELIVERED', 'SHIPPED')
# Abandon unpaid orders created at checkout (hours); management command uses this default
STALE_PENDING_ORDER_HOURS = 72


META_SITE_PROTOCOL = 'http', 'https'


ROOT_URLCONF = 'snm.urls'

LOGIN_REDIRECT_URL = 'homepage'

LOGIN_URL = '/login/'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'snmov',
    'icvybz',
    'feedback',
    'crispy_forms',
    'storages',
    'django.contrib.sitemaps',
    'tinymce',
    'meta',
    'crispy_bootstrap4',
    'bootstrap4',
    
]

SITE_ID = 1
SITE_DOMAIN = 'justvybz.com'
SITE_NAME = 'Justvybz'

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap4'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Extended user (email verification) — must match snmov.models.User
AUTH_USER_MODEL = 'snmov.User'

TINYMCE_DEFAULT_CONFIG = {
    'height': 360,
    'width': 'auto',
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    # 'content_css': '../static-root/snmov/css/sm.css',
    'contents_style': 'body {font-family: Cabin; }',
    'theme': 'modern',
    'plugins': '''
            textcolor save link image media preview codesample contextmenu
            table code lists fullscreen  insertdatetime  nonbreaking
            contextmenu directionality searchreplace wordcount visualblocks
            visualchars code fullscreen autolink lists  charmap print  hr
            anchor pagebreak emoticons
            ''',
    'toolbar1': '''
            fullscreen preview bold italic underline | fontselect,
            fontsizeselect  | forecolor backcolor | alignleft alignright |
            aligncenter alignjustify | indent outdent | bullist numlist table |
            | link image media | codesample | emoticons |
            ''',
    'toolbar2': '''
            visualblocks visualchars |
            charmap hr pagebreak nonbreaking anchor |  code |
            ''',
    'contextmenu': 'formats | link image',
    'menubar': True,
    'statusbar': True,
}

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "snm.context_processors.cart_context",
                "snm.context_processors.cart_count",
            ],
        },
    },
]

WSGI_APPLICATION = 'snm.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Toronto'

USE_I18N = True

USE_L10N = True


db_from_env = dj_database_url.config(conn_max_age=500)
# DATABASES['default'].update(db_from_env)

# Test database configuration (use SQLite in-memory for tests)
import sys
if 'test' in sys.argv or 'pytest' in sys.modules:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Login brute-force protection (icvybz login_api). Window is intentionally
# short so locked-out users are not stuck for an hour after typos.
LOGIN_RATE_LIMIT_MAX = 10
LOGIN_RATE_LIMIT_WINDOW_SECONDS = 600  # 10 minutes

# Force HTTPS for password reset emails
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'

# Email configuration
DEFAULT_FROM_EMAIL = 'justvybz@justvybz.com'
SUPPORT_EMAIL = 'justvybz@justvybz.com'

EMAIL_HOST = 'mail.papamail.net'
EMAIL_PORT = 587
EMAIL_HOST_USER = config.get('section', 'VYBZ_FB_USER')
EMAIL_HOST_PASSWORD = config.get('section', 'VYBZ_FB_PASS')
EMAIL_USE_TLS = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'  # Required for staticfiles app
STATIC_ROOT = os.path.join(BASE_DIR, 'live-static',
                           'static-root')  # live cdn AWS S3

# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# File upload settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# In-scene ads: only on platform standard GLB scenes (see icvybz.ad_services.season_supports_platform_ads)
AD_ENABLED_MODEL_BASENAMES = [
    'cof_animation_clean.v3.2',
]
AD_PLACEMENT_CACHE_SECONDS = 120


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'frontend', 'build', 'static'),  # React build static files (js, css, media) - point directly to static/ subdirectory to avoid double "static/" in S3 path
]

# Default Sender Address (fallback if admin user's address is not found)
DEFAULT_SENDER_NAME = 'Justvybz Inc.'
DEFAULT_SENDER_STREET1 = '206 Winston Blvd'
DEFAULT_SENDER_STREET2 = ''
DEFAULT_SENDER_CITY = 'Cambridge'
DEFAULT_SENDER_STATE = 'ON'
DEFAULT_SENDER_ZIP = 'N3C 1M3'
DEFAULT_SENDER_COUNTRY = 'CA'

# Allow hosts
ALLOWED_HOSTS = [
    'justvybz.com',
    'www.justvybz.com',
]

# Django REST Framework configuration
REST_FRAMEWORK = {
    # Token first: SPA sends Authorization; avoids SessionAuthentication CSRF on unsafe methods
    # when a Django session cookie exists (e.g. admin). Session remains for tests / session-only clients.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    # Rate limiting for API endpoints (OWASP, NIST compliance)
    # Scoped rates apply via snmov.throttling.* on sensitive views.
    # Production overrides these downward in snm.settings.pro.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'password_reset': '10/hour',
        'register': '20/hour',
        'checkout': '40/hour',
        'newsletter': '10/hour',
        'contact': '10/hour',
    },
    'EXCEPTION_HANDLER': 'snmov.api_exceptions.api_exception_handler',
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# Session settings - ensure session cookie is sent with cross-origin requests
SESSION_COOKIE_SAMESITE = 'Lax'  # Allows session cookie to be sent with cross-origin requests
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_SAVE_EVERY_REQUEST = True  # Save session on every request to keep it alive
