# Generated by Django 3.2.20 on 2025-01-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimage',
            name='object_id',
            field=models.UUIDField(null=True),
        ),
    ]
