# Generated by Django 3.2.20 on 2025-01-25 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0002_alter_siteimage_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snmov.product'),
        ),
    ]
