# Generated by Django 3.2.20 on 2025-05-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0007_shippingaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_rate_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
