# Generated by Django 3.2.20 on 2025-05-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0010_auto_20250515_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='package_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='package_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ORDERED', 'Ordered'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
    ]
