# Generated by Django 3.2.20 on 2025-05-16 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0013_auto_20250516_2344'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='snmov_user',
        ),
    ]
