# Generated by Django 3.2.20 on 2025-05-17 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0014_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='snmov_User',
        ),
    ]
