# Generated by Django 3.2.20 on 2025-05-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0017_auto_20250518_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimage',
            name='object_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
