# Generated by Django 3.2.20 on 2025-12-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0018_alter_siteimage_object_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name_plural': 'ShippingAddress'},
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default saved address for this user'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='is_saved',
            field=models.BooleanField(default=False, help_text='Whether this is a saved address for future use'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='label',
            field=models.CharField(blank=True, help_text="Label for saved address (e.g., 'Home', 'Work')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
