# Generated by Django 3.2.20 on 2025-12-03 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snmov', '0020_add_product_notification_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'ShippingAddress'},
        ),
        migrations.RemoveField(
            model_name='productnotification',
            name='notification_sent',
        ),
        migrations.RemoveField(
            model_name='productnotification',
            name='notification_sent_at',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='is_saved',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='label',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='EmailPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketing_emails', models.BooleanField(default=True, help_text='Receive marketing and promotional emails')),
                ('product_notifications', models.BooleanField(default=True, help_text='Receive product back in stock notifications')),
                ('order_updates', models.BooleanField(default=True, help_text='Receive order status update emails')),
                ('cart_reminders', models.BooleanField(default=True, help_text='Receive abandoned cart reminder emails')),
                ('collaboration_notifications', models.BooleanField(default=True, help_text='Receive collaboration invitation and request emails')),
                ('newsletter', models.BooleanField(default=False, help_text='Subscribe to newsletter')),
                ('unsubscribe_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('unsubscribe_token_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Preference',
                'verbose_name_plural': 'Email Preferences',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(help_text="Type of email (e.g., 'order_confirmation', 'welcome')", max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('bounced', models.BooleanField(default=False)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['email_type', 'status'], name='snmov_email_email_t_e66b33_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['recipient_email', 'created_at'], name='snmov_email_recipie_57b192_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['recipient_user', 'created_at'], name='snmov_email_recipie_6b8c90_idx'),
        ),
    ]
