# Generated by Django 3.2.20 on 2025-12-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmov', '0023_add_security_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='method',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
