# Generated by Django 3.2.20 on 2025-08-26 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('personality', models.CharField(blank=True, max_length=50)),
                ('love_interest', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('model_file', models.FileField(upload_to='characters/')),
                ('is_public', models.BooleanField(default=False, help_text='Make this character visible to other users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('comic_image', models.ImageField(blank=True, null=True, upload_to='comic_images/')),
                ('is_public', models.BooleanField(default=False, help_text='Make this comic visible to other users')),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('episode_number', models.PositiveIntegerField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='episode_covers/')),
                ('is_published', models.BooleanField(default=False, help_text='Check this to make the episode visible on the website')),
                ('summary', models.TextField(blank=True, help_text='Summary and lead-in for the next episode')),
                ('summary_camera_orbit', models.CharField(blank=True, help_text="Camera position for episode summary (e.g., '0deg 75deg 5m')", max_length=50)),
                ('summary_field_of_view', models.FloatField(default=60.0, help_text='Field of view for episode summary in degrees')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this episode has been viewed')),
                ('last_viewed', models.DateTimeField(auto_now=True, help_text='Last time this episode was viewed')),
            ],
        ),
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Intersection', max_length=100)),
                ('model_gltf', models.FileField(blank=True, null=True, upload_to='intersections/')),
                ('model_usdz', models.FileField(blank=True, null=True, upload_to='intersections/')),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Make this intersection visible to other users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intersections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('google', 'Google Search'), ('social', 'Social Media'), ('referral', 'Referral'), ('email', 'Email'), ('other', 'Other')], max_length=20)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_sources', to='icvybz.episode')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField(null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField()),
                ('model_gltf', models.FileField(blank=True, null=True, upload_to='models/')),
                ('model_usdz', models.FileField(blank=True, null=True, upload_to='models/')),
                ('comic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='icvybz.comic')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='icvybz.episode')),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='icvybz.intersection')),
            ],
        ),
        migrations.CreateModel(
            name='POV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('head_x', models.FloatField(default=0.0, help_text="Character's head X coordinate in world space")),
                ('head_y', models.FloatField(default=1.6, help_text="Character's head Y coordinate (approx. head height)")),
                ('head_z', models.FloatField(default=0.0, help_text="Character's head Z coordinate in world space")),
                ('default_camera_target', models.CharField(default='0m 1.6m 0m', help_text="Default point the camera looks at for this POV (e.g., '0m 1.6m 0m')", max_length=50)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='povs', to='icvybz.character')),
                ('scenes', models.ManyToManyField(related_name='povs', to='icvybz.Scene')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='icvybz.season'),
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('scene_title', models.CharField(blank=True, max_length=100)),
                ('scene_description', models.TextField(blank=True, max_length=250)),
                ('shot_type', models.CharField(choices=[('closeUp', 'Close Up'), ('mediumShot', 'Medium Shot'), ('wideShot', 'Wide Shot'), ('heroShot', 'Hero Shot (Low Angle)'), ('vulnerableShot', 'Vulnerable Shot (High Angle)'), ('overShoulder', 'Over the Shoulder'), ('confrontation', 'Confrontation Shot')], default='mediumShot', help_text='Select a camera preset for this dialogue', max_length=20)),
                ('camera_orbit', models.CharField(default='0deg 75deg 3m', help_text="Camera position in degrees and meters (e.g., '0deg 75deg 3m')", max_length=50)),
                ('camera_target', models.CharField(blank=True, help_text="Optional override for the camera target point (e.g., '0m 1.6m 0m'). If empty, uses POV's default target.", max_length=50, null=True)),
                ('field_of_view', models.FloatField(default=45.0, help_text='Camera field of view in degrees')),
                ('zoom_speed', models.FloatField(default=1.0, help_text='Speed of camera transitions')),
                ('rotation', models.CharField(default='0deg 0deg 0deg', help_text="Model rotation in degrees (e.g., '0deg 0deg 0deg')", max_length=50)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='icvybz.episode')),
                ('pov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='icvybz.pov')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ComicComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_cont', models.TextField(max_length=200, verbose_name='Comment')),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='icvybz.episode')),
                ('user_name', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-comment_date'],
            },
        ),
    ]
