# Generated by Django 3.2.20 on 2025-10-16 20:47

from django.db import migrations
from django.utils import timezone


def populate_timestamps_for_existing_data(apps, schema_editor):
    """
    Populate timestamp fields for existing data that was created before these fields existed.
    This ensures seamless import of comics from other Django apps.
    """
    Comic = apps.get_model('icvybz', 'Comic')
    Season = apps.get_model('icvybz', 'Season')
    Episode = apps.get_model('icvybz', 'Episode')
    Dialogue = apps.get_model('icvybz', 'Dialogue')
    
    # Use current time for all existing records
    now = timezone.now()
    
    # Update existing comics
    Comic.objects.filter(created_at__isnull=True).update(created_at=now, updated_at=now)
    
    # Update existing seasons
    Season.objects.filter(created_at__isnull=True).update(created_at=now, updated_at=now)
    
    # Update existing episodes
    Episode.objects.filter(created_at__isnull=True).update(created_at=now, updated_at=now)
    
    # Update existing dialogues
    Dialogue.objects.filter(created_at__isnull=True).update(created_at=now, updated_at=now)


def reverse_populate_timestamps(apps, schema_editor):
    """
    Reverse migration - set timestamps to None for existing data.
    This is not recommended but provided for completeness.
    """
    Comic = apps.get_model('icvybz', 'Comic')
    Season = apps.get_model('icvybz', 'Season')
    Episode = apps.get_model('icvybz', 'Episode')
    Dialogue = apps.get_model('icvybz', 'Dialogue')
    
    # Set timestamps to None (this will cause issues with auto_now fields)
    Comic.objects.all().update(created_at=None, updated_at=None)
    Season.objects.all().update(created_at=None, updated_at=None)
    Episode.objects.all().update(created_at=None, updated_at=None)
    Dialogue.objects.all().update(created_at=None, updated_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('icvybz', '0004_auto_20251016_2040'),
    ]

    operations = [
        migrations.RunPython(
            populate_timestamps_for_existing_data,
            reverse_populate_timestamps,
        ),
    ]