# Generated by Django 3.2.20 on 2025-10-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icvybz', '0005_auto_20251016_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiotrack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created. Nullable for imports from other Django apps.', null=True),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated. Nullable for imports from other Django apps.', null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created. Nullable for imports from other Django apps.', null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated. Nullable for imports from other Django apps.', null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created. Nullable for imports from other Django apps.', null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated. Nullable for imports from other Django apps.', null=True),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created. Nullable for imports from other Django apps.', null=True),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated. Nullable for imports from other Django apps.', null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created. Nullable for imports from other Django apps.', null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated. Nullable for imports from other Django apps.', null=True),
        ),
        migrations.AlterField(
            model_name='intersection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created. Nullable for imports from other Django apps.', null=True),
        ),
        migrations.AlterField(
            model_name='intersection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated. Nullable for imports from other Django apps.', null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created. Nullable for imports from other Django apps.', null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated. Nullable for imports from other Django apps.', null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created. Nullable for imports from other Django apps.', null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated. Nullable for imports from other Django apps.', null=True),
        ),
    ]
