# Generated by Django 3.2.20 on 2025-10-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icvybz', '0010_collaboration_models'),
    ]

    operations = [
        # Index for story filtering by user and public status
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_comic_user_public ON icvybz_comic (user_id, is_public);",
            reverse_sql="DROP INDEX IF EXISTS idx_comic_user_public;"
        ),
        
        # Index for season filtering by comic
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_season_comic ON icvybz_season (comic_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_season_comic;"
        ),
        
        # Index for episode filtering by season and published status
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_episode_season ON icvybz_episode (season_id, is_published);",
            reverse_sql="DROP INDEX IF EXISTS idx_episode_season;"
        ),
        
        # Index for dialogue filtering by episode and order
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_dialogue_episode ON icvybz_dialogue (episode_id, \"order\");",
            reverse_sql="DROP INDEX IF EXISTS idx_dialogue_episode;"
        ),
        
        # Index for collaboration queries
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_story_collaborator_user ON icvybz_storycollaborator (user_id, is_active);",
            reverse_sql="DROP INDEX IF EXISTS idx_story_collaborator_user;"
        ),
        
        # Index for studio collaborators
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_studio_collaborator_user ON icvybz_studiocollaborator (user_id, is_active);",
            reverse_sql="DROP INDEX IF EXISTS idx_studio_collaborator_user;"
        ),
        
        # Index for story collaborators
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_story_collaborator_story ON icvybz_storycollaborator (story_id, is_active);",
            reverse_sql="DROP INDEX IF EXISTS idx_story_collaborator_story;"
        ),
    ]