# Generated by Django 3.2.20 on 2026-01-27 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icvybz', '0016_allow_multiple_roles_per_collaborator'),
        ('snmov', '0025_add_return_models'),
        ('feedback', '0002_add_related_foreign_keys'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feedbackticket',
            name='feedback_fe_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedbackticket',
            name='feedback_fe_priority_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedbackticket',
            name='feedback_fe_assigned_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedbackticket',
            name='feedback_fe_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedbackticket',
            name='feedback_fe_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedbackticket',
            name='feedback_fe_ticket_n_idx',
        ),
        migrations.AlterField(
            model_name='feedbackticket',
            name='related_episode',
            field=models.ForeignKey(blank=True, db_column='related_episode_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_tickets', to='icvybz.episode'),
        ),
        migrations.AlterField(
            model_name='feedbackticket',
            name='related_order',
            field=models.ForeignKey(blank=True, db_column='related_order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_tickets', to='snmov.order'),
        ),
        migrations.AlterField(
            model_name='feedbackticket',
            name='related_story',
            field=models.ForeignKey(blank=True, db_column='related_story_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_tickets', to='icvybz.comic'),
        ),
        migrations.AlterField(
            model_name='feedbackticket',
            name='related_studio',
            field=models.ForeignKey(blank=True, db_column='related_studio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_tickets', to='icvybz.studio'),
        ),
        migrations.AddIndex(
            model_name='feedbackticket',
            index=models.Index(fields=['status'], name='feedback_fe_status_f5853a_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackticket',
            index=models.Index(fields=['priority'], name='feedback_fe_priorit_2dd3da_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackticket',
            index=models.Index(fields=['assigned_to'], name='feedback_fe_assigne_64afd7_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackticket',
            index=models.Index(fields=['category'], name='feedback_fe_categor_73f093_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackticket',
            index=models.Index(fields=['created_at'], name='feedback_fe_created_f6777d_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackticket',
            index=models.Index(fields=['ticket_number'], name='feedback_fe_ticket__301a3e_idx'),
        ),
    ]
