# Generated by Django 5.2.3 on 2026-04-09 01:44

import django.core.validators
import django.db.models.deletion
import vybcheq.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('rules', models.JSONField(default=vybcheq.models._default_rules, help_text='List of rules, e.g. [{"metric": "pe_ratio", "op": "<=", "value": 25}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreenRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('universe_note', models.CharField(blank=True, help_text='e.g. watchlist only, TSX + NASDAQ, …', max_length=255)),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screen_runs', to='vybcheq.screeningruleset')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('exchange', models.CharField(db_index=True, max_length=64)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('sector', models.CharField(blank=True, max_length=128)),
                ('industry', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('cik', models.CharField(blank=True, help_text='US SEC CIK, if applicable.', max_length=32, verbose_name='CIK')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'securities',
                'ordering': ['exchange', 'symbol'],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'exchange'), name='vybcheq_security_symbol_exchange_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ResearchPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.JSONField(default=vybcheq.models._default_sections)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_packet', to='vybcheq.security')),
            ],
            options={
                'ordering': ['security__symbol'],
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold'), ('pass', 'Pass')], max_length=16)),
                ('thesis', models.TextField()),
                ('risk', models.TextField()),
                ('invalidation', models.TextField(blank=True, help_text='What would prove this thesis wrong?')),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('notional', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='vybcheq.security')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='1 = highest', validators=[django.core.validators.MinValueValidator(1)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('security', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entry', to='vybcheq.security')),
            ],
            options={
                'ordering': ['priority', 'security__symbol'],
            },
        ),
        migrations.CreateModel(
            name='ScreenResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField()),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('metrics_snapshot', models.JSONField(default=vybcheq.models._default_metrics_snapshot, help_text='Numeric inputs used for this pass/fail.')),
                ('details', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_results', to='vybcheq.screenrun')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_results', to='vybcheq.security')),
            ],
            options={
                'ordering': ['-passed', 'score'],
                'constraints': [models.UniqueConstraint(fields=('run', 'security'), name='vybcheq_screenresult_run_security_uniq')],
            },
        ),
    ]
