# Generated by Django 5.2.3 on 2026-04-09 01:57

import vybcheq.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vybcheq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='screening_metrics',
            field=models.JSONField(blank=True, default=vybcheq.models._default_metrics_snapshot, help_text='Numbers used by vibe-check rules, e.g. {"pe_ratio": 18.2, "roe": 0.14}'),
        ),
    ]
