# Generated by Django 5.2.3 on 2026-04-10 02:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vybcheq', '0002_security_screening_metrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='quote_last_price',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Cached last price (Yahoo); used for simulated marks. 1 cheq ≈ 1 USD notional.', max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='security',
            name='quote_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CheqAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=4, default=Decimal('10000'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cheq_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cheq account',
                'verbose_name_plural': 'cheq accounts',
            },
        ),
        migrations.CreateModel(
            name='SimPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheqs_opened', models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=24)),
                ('shares', models.DecimalField(decimal_places=12, max_digits=24)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('cheqs_proceeds', models.DecimalField(blank=True, decimal_places=4, help_text='Cheqs returned to wallet on close.', max_digits=20, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sim_positions', to='vybcheq.security')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='PositionMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=8, max_digits=24)),
                ('value_cheqs', models.DecimalField(decimal_places=4, max_digits=20)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='vybcheq.simposition')),
            ],
            options={
                'ordering': ['marked_at'],
            },
        ),
    ]
