# Generated by Django 3.2.20 on 2024-11-01 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='tilf.episode'),
        ),
    ]
