# Generated by Django 3.2.20 on 2024-11-02 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0002_scene_episode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pov',
            name='scene',
        ),
        migrations.AddField(
            model_name='dialogue',
            name='episode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tilf.episode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pov',
            name='scenes',
            field=models.ManyToManyField(related_name='povs', to='tilf.Scene'),
        ),
        migrations.AddField(
            model_name='pov',
            name='title',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
