# Generated by Django 3.2.20 on 2024-11-02 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0003_auto_20241102_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='scene',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='tilf.scene'),
            preserve_default=False,
        ),
    ]
