# Generated by Django 3.2.20 on 2024-11-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0004_dialogue_scene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pov',
            name='bubble_position',
        ),
        migrations.RemoveField(
            model_name='pov',
            name='camera_angle',
        ),
        migrations.AddField(
            model_name='pov',
            name='angle_x',
            field=models.FloatField(default=0.0, help_text='Camera angle around the X-axis in degrees'),
        ),
        migrations.AddField(
            model_name='pov',
            name='angle_y',
            field=models.FloatField(default=0.0, help_text='Camera angle around the Y-axis in degrees'),
        ),
        migrations.AddField(
            model_name='pov',
            name='angle_z',
            field=models.FloatField(default=0.0, help_text='Camera angle around the Z-axis in degrees'),
        ),
        migrations.AddField(
            model_name='pov',
            name='bubble_position_x',
            field=models.FloatField(default=0.0, help_text='X coordinate for placing text bubble'),
        ),
        migrations.AddField(
            model_name='pov',
            name='bubble_position_y',
            field=models.FloatField(default=0.0, help_text='Y coordinate for placing text bubble'),
        ),
        migrations.AlterField(
            model_name='pov',
            name='zoom_level',
            field=models.FloatField(default=1.0, help_text='Zoom level for the camera, where 1.0 is normal zoom'),
        ),
    ]
