# Generated by Django 3.2.20 on 2025-02-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0005_auto_20241103_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='love_interest',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='personality',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
