# Generated by Django 3.2.20 on 2025-02-05 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0007_comic'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='comic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='tilf.comic'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
