# Generated by Django 3.2.20 on 2025-02-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0008_auto_20250205_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='camera_orbit',
            field=models.CharField(default='0deg 75deg 3m', max_length=50),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='camera_target',
            field=models.CharField(default='0m 0m 0m', max_length=50),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='field_of_view',
            field=models.FloatField(default=45.0),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='rotation',
            field=models.CharField(default='0deg 0deg 0deg', max_length=50),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='zoom_speed',
            field=models.FloatField(default=1.0),
        ),
    ]
