# Generated by Django 3.2.20 on 2025-02-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0009_auto_20250208_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intersection',
            name='model_file',
        ),
        migrations.AddField(
            model_name='intersection',
            name='model_gltf',
            field=models.FileField(blank=True, null=True, upload_to='intersections/'),
        ),
        migrations.AddField(
            model_name='intersection',
            name='model_usdz',
            field=models.FileField(blank=True, null=True, upload_to='intersections/'),
        ),
    ]
