# Generated by Django 3.2.20 on 2025-02-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0010_auto_20250208_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pov',
            name='bubble_position_x',
        ),
        migrations.RemoveField(
            model_name='pov',
            name='bubble_position_y',
        ),
        migrations.AddField(
            model_name='pov',
            name='head_x',
            field=models.FloatField(default=0.0, help_text="Character's head X coordinate in world space"),
        ),
        migrations.AddField(
            model_name='pov',
            name='head_y',
            field=models.FloatField(default=1.6, help_text="Character's head Y coordinate (approx. head height)"),
        ),
        migrations.AddField(
            model_name='pov',
            name='head_z',
            field=models.FloatField(default=0.0, help_text="Character's head Z coordinate in world space"),
        ),
        migrations.AlterField(
            model_name='pov',
            name='angle_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pov',
            name='angle_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pov',
            name='angle_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pov',
            name='zoom_level',
            field=models.FloatField(default=1.0),
        ),
    ]
