# Generated by Django 3.2.20 on 2025-02-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0011_auto_20250208_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
