# Generated by Django 3.2.20 on 2025-02-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0012_alter_scene_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
