# Generated by Django 3.2.20 on 2025-02-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0014_alter_scene_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='season_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
