# Generated by Django 3.2.20 on 2025-06-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0015_season_season_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='shot_type',
            field=models.CharField(choices=[('closeUp', 'Close Up'), ('mediumShot', 'Medium Shot'), ('wideShot', 'Wide Shot'), ('heroShot', 'Hero Shot (Low Angle)'), ('vulnerableShot', 'Vulnerable Shot (High Angle)'), ('overShoulder', 'Over the Shoulder'), ('confrontation', 'Confrontation Shot')], default='mediumShot', help_text='Select a camera preset for this dialogue', max_length=20),
        ),
    ]
