# Generated by Django 3.2.20 on 2025-06-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0016_dialogue_shot_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pov',
            name='angle_x',
        ),
        migrations.RemoveField(
            model_name='pov',
            name='angle_y',
        ),
        migrations.RemoveField(
            model_name='pov',
            name='angle_z',
        ),
        migrations.RemoveField(
            model_name='pov',
            name='zoom_level',
        ),
        migrations.AddField(
            model_name='pov',
            name='default_camera_target',
            field=models.CharField(default='0m 1.6m 0m', help_text="Default point the camera looks at for this POV (e.g., '0m 1.6m 0m')", max_length=50),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='camera_orbit',
            field=models.CharField(default='0deg 75deg 3m', help_text="Camera position in degrees and meters (e.g., '0deg 75deg 3m')", max_length=50),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='camera_target',
            field=models.CharField(blank=True, help_text="Optional override for the camera target point (e.g., '0m 1.6m 0m'). If empty, uses POV's default target.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='field_of_view',
            field=models.FloatField(default=45.0, help_text='Camera field of view in degrees'),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='rotation',
            field=models.CharField(default='0deg 0deg 0deg', help_text="Model rotation in degrees (e.g., '0deg 0deg 0deg')", max_length=50),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='zoom_speed',
            field=models.FloatField(default=1.0, help_text='Speed of camera transitions'),
        ),
    ]
