# Generated by Django 3.2.20 on 2025-06-11 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0017_auto_20250610_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialogue',
            options={'ordering': ['scene', 'order']},
        ),
        migrations.AddField(
            model_name='episode',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='episode_covers/'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='tilf.episode'),
        ),
    ]
