# Generated by Django 3.2.20 on 2025-06-11 23:30

from django.db import migrations, models
import django.db.models.deletion


def create_default_intersection(apps, schema_editor):
    Intersection = apps.get_model('tilf', 'Intersection')
    Season = apps.get_model('tilf', 'Season')
    
    # Create default intersection if none exists
    default_intersection, created = Intersection.objects.get_or_create(
        name='Default Intersection'
    )
    
    # Update all seasons to use the default intersection
    Season.objects.filter(intersection__isnull=True).update(intersection=default_intersection)


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0018_auto_20250611_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialogue',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='scene',
        ),
        migrations.AddField(
            model_name='dialogue',
            name='scene_description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='scene_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        # Add the field as nullable
        migrations.AddField(
            model_name='season',
            name='intersection',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='tilf.intersection'),
        ),
        # Run the data migration to set default values
        migrations.RunPython(create_default_intersection),
        # Then make the field required
        migrations.AlterField(
            model_name='season',
            name='intersection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='tilf.intersection'),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='tilf.episode'),
        ),
    ]
