# Generated by Django 3.2.20 on 2025-06-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0020_remove_social_media_content_object'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMediaLink',
        ),
        migrations.RemoveField(
            model_name='season',
            name='intersection',
        ),
        migrations.AddField(
            model_name='season',
            name='model_gltf',
            field=models.FileField(blank=True, null=True, upload_to='models/'),
        ),
        migrations.AddField(
            model_name='season',
            name='model_usdz',
            field=models.FileField(blank=True, null=True, upload_to='models/'),
        ),
    ]
