# Generated by Django 3.2.20 on 2025-06-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0021_auto_20250611_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='season_image',
            field=models.ImageField(blank=True, null=True, upload_to='season_images/'),
        ),
    ]
