# Generated by Django 3.2.20 on 2025-06-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0022_season_season_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='season_image',
        ),
        migrations.AddField(
            model_name='comic',
            name='comic_image',
            field=models.ImageField(blank=True, null=True, upload_to='comic_images/'),
        ),
    ]
