# Generated by Django 3.2.20 on 2025-06-14 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tilf', '0023_auto_20250613_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_cont', models.TextField(max_length=200, verbose_name='Comment')),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('comment_comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tilf.episode')),
                ('user_name', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-comment_date'],
            },
        ),
    ]
