# Generated by Django 3.2.20 on 2025-06-14 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0024_comiccomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comiccomment',
            old_name='comment_comic',
            new_name='episode',
        ),
    ]
