# Generated by Django 5.2.3 on 2025-07-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0025_rename_comment_comic_comiccomment_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Check this to make the episode visible on the website'),
        ),
    ]
