# Generated by Django 5.2.3 on 2025-07-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0026_episode_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='summary',
            field=models.TextField(blank=True, help_text='Summary and lead-in for the next episode'),
        ),
    ]
