# Generated by Django 5.2.3 on 2025-07-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0027_episode_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='summary_camera_orbit',
            field=models.CharField(blank=True, help_text="Camera position for episode summary (e.g., '0deg 75deg 5m')", max_length=50),
        ),
        migrations.AddField(
            model_name='episode',
            name='summary_field_of_view',
            field=models.FloatField(default=60.0, help_text='Field of view for episode summary in degrees'),
        ),
    ]
