# Generated by Django 5.2.3 on 2025-07-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilf', '0028_episode_summary_camera_orbit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True, help_text='Last time this episode was viewed'),
        ),
        migrations.AddField(
            model_name='episode',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this episode has been viewed'),
        ),
    ]
